# Generated by Django 4.0.2 on 2022-02-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sequence', models.IntegerField(unique=True)),
                ('no_of_compounds', models.IntegerField()),
                ('bonus_start_perc', models.FloatField()),
                ('bonus_multiplier', models.FloatField()),
            ],
        ),
    ]
